// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/bun";
import { initializeLogger, getLogger } from "~/lib/core/logger/logger.server";

// Initialize LogTape only in production (development uses entry.server.tsx)
if (process.env.NODE_ENV === 'production') {
  await initializeLogger();
}

const server = await createHonoServer();

// Log server startup only in production
if (process.env.NODE_ENV === 'production') {
  const port = process.env.PORT || 3000;
  const nodeEnv = process.env.NODE_ENV || 'development';

  getLogger().info('Starting Abaqus Job Manager server', 'SERVER_STARTUP', {
    port,
    environment: nodeEnv,
    bunVersion: Bun.version,
    timestamp: new Date().toISOString()
  });

  getLogger().info('Server started successfully', 'SERVER_READY', {
    port,
    environment: nodeEnv,
    pid: process.pid
  });
}

// Handle graceful shutdown (production only)
const gracefulShutdown = (signal: string) => {
  if (process.env.NODE_ENV === 'production') {
    getLogger().info('Received shutdown signal', 'SERVER_SHUTDOWN', {
      signal,
      uptime: process.uptime(),
      timestamp: new Date().toISOString()
    });
  }
  
  process.exit(0);
};

process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
process.on('SIGINT', () => gracefulShutdown('SIGINT'));

export default server;
