// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/bun";
import { getLogger, initializeLogger } from "~/lib/core/logger/logger.server";
import { initializeServer } from "~/server/controller";
import { env } from "./lib/core/env";

// Initialize LogTape only in production (development uses entry.server.tsx)
if (env.NODE_ENV === "production") {
	await initializeLogger();
}

const server = await createHonoServer();

// Initialize server services (job execution scheduler, etc.)
await initializeServer({
	enableJobExecution: true,
	jobExecutionConfig: {
		checkIntervalSeconds: 30,
		maxConcurrentJobs: 3,
	},
});

// Log server startup only in production
if (env.NODE_ENV === "production") {
	getLogger().info("Starting Abaqus Job Manager server", {
		pid: process.pid,
		port: env.PORT,
		environment: env.NODE_ENV,
		bunVersion: Bun.version,
		timestamp: new Date().toISOString(),
	});
}

// Note: Graceful shutdown is now handled by the unified SchedulerSystem
// via ServerInitializationService.initializeServer()

export default server;
